version: '3.9'
services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
#  zookeeper-2:
#    image: confluentinc/cp-zookeeper
#    environment:
#      ZOOKEEPER_SERVER_ID: 2
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000
#    ports:
#      - 32181:2181

  kafka-1:
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper-1
    ports:
      - 29092:29092
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_BROKER_ID: 1
      KAFKA_CREATE_TOPICS: "teams:1:1"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
#  kafka-2:
#    image: confluentinc/cp-kafka
#    depends_on:
#      - zookeeper-2
#    ports:
#      - 39092:39092
#    environment:
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092,PLAINTEXT_HOST://localhost:39092
#      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
#      KAFKA_BROKER_ID: 2
#      KAFKA_CREATE_TOPICS: "operations:1:1"
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper-2:2181

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8181:8181
    depends_on:
      - zookeeper-1
#      - zookeeper-2
      - kafka-1
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper-1:2181
#      KAFKA_CLUSTERS_1_NAME: secondLocal
#      KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS: kafka-2:9092
#      KAFKA_CLUSTERS_1_ZOOKEEPER: zookeeper-2:2181
      SERVER_PORT: 8181
